<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<div>
    <h1>Welcome to the AjaxAction View Helper Demo</h1>
    <ul>
        <li><a href="/index/sync">open the oldschool version (synchronous)</a></li>
        <li><a href="/index/async">REFRESH ME AND WATCH FIREBUG!!!</a></li>
    </ul>
    
    <h3>This is a REALLY expensive navigation</h3>
    <?php echo $this->ajaxAction('getnavigation', 'content', null, array(), '_partials/ajax.phtml'); ?>
 
    <h3>This is the content</h3>
    <?php echo $this->ajaxAction('getcontent', 'content', null, array(), '_partials/ajax.phtml'); ?>
    
    <h3>This is a cool result of a call to the Twitter-API</h3>
    <?php echo $this->ajaxAction('gettweets', 'content', null, array(), '_partials/ajax.phtml'); ?>
</div>