<!-- script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script -->
<div>
    <h1>Welcome to the AjaxAction View Helper Demo</h1>
    <ul>
        <li><a href="/index/sync">open the oldschool version (synchronous)</a></li>
        <li><a href="/index/async">open the same page using AjaxAction helper</a></li>
    </ul>
    
    <h2>Hint</h2>
    Have a look at Firebug's network tab and refresh the page in short intervals. Actions will be cache for 20 senconds, so You will see interesting requests ;-)
</div>